app            = "accesslens"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  ASPNETCORE_FORWARDEDHEADERS_ENABLED = "true"
  ASPNETCORE_URLS           = "http://+:8080"
  SKIP_PLAYWRIGHT_INSTALL   = "1"
  ConnectonStrings__Sqlite  = "Data Source=/data/accesslens.db"
  S3__Region                = "us-east-2"
  S3__BucketName            = accesslens-prod-reports
  SendGrid__FromEmail       = "derek@getaccesslens.com"
  AWS_ACCESS_KEY_ID         = "AKIAYCFEYLAYYRRHLU45"

[[vm]]
  # applies to all process groups
  size   = "shared-cpu-1x"
  memory = "512mb"

[processes]
  app = "/entrypoint.sh"

[[services]]
  processes     = ["app"]
  internal_port = 8080
  protocol      = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port     = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port     = 443


  [[services.http_checks]]
    processes = ["app"]
    port      = 80
    method    = "get"
    path      = "/api/health"
    interval  = "30s"
    timeout   = "5s"

[[mounts]]
  source      = "data"
  destination = "/data"