app            = "accesslens"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  ASPNETCORE_FORWARDEDHEADERS_ENABLED = "true"
  ASPNETCORE_URLS          = "http://+:8080"
  SKIP_PLAYWRIGHT_INSTALL  = "1"
  MINIO_ROOT_USER          = "minioadmin"
  ConnectonStrings__Sqlite = "Data Source=/data/accesslens.db"
  S3__SERVICE_URL           = "http://accesslens.internal:9000"
  S3__REGION                = "us-east-1"
  SendGrid__FromEmail       = "derek@getaccesslens.com"

[processes]
  app = "/entrypoint.sh"

[[services]]
  processes     = ["app"]
  internal_port = 8080
  protocol      = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port     = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port     = 443

  # Expose MinIO S3 API internally (no handlers by default)
  [[services.ports]]
    processes = ["app"]
    port = 9000

  [[services.http_checks]]
    processes = ["app"]
    port      = 80
    method    = "get"
    path      = "/api/health"
    interval  = "30s"
    timeout   = "5s"

[[mounts]]
  source      = "data"
  destination = "/data"