name: Refresh marketing sample
on:
  push:
    paths: 'AccessLensApi/Features/Reports/Templates/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4                # checks out *application* repo
      - uses: actions/setup-dotnet@v4
        with: { dotnet-version: '8.0.x' }

      # ▶ generate HTML + PDF ---------------------------------------------
      - name: Build solution
        run: dotnet build AccessLensCli.sln --configuration Release
      - name: Install Playwright browsers
        run: dotnet playwright install --with-deps
      
      - run: dotnet run --project AccessLensApi.Tools/GenerateSample --output /tmp/sample

      # ▶ check out marketing repo as second remote -----------------------
      - name: Checkout marketing site
        uses: actions/checkout@v4
        with:
          repository: derekbolyard/AccessLensLanding
          path: marketing
          token: ${{ secrets.MARKETING_REPO_PAT }}

      # ▶ copy & commit
      - name: Copy assets
        run: |
          mkdir -p marketing/public/samples
          cp /tmp/sample/report-sample.{html,pdf} marketing/public/samples/
      - name: Commit & push
        run: |
          cd marketing
          git config user.name  "accesslens-bot"
          git config user.email "bot@users.noreply.github.com"
          git add public/samples/*
          git commit -m "chore: refresh sample audit" || echo "no changes"
          git push
        env:
          GIT_AUTHOR_NAME:  "accesslens-bot"
          GIT_AUTHOR_EMAIL: "bot@users.noreply.github.com"
          GIT_COMMITTER_NAME:  "accesslens-bot"
          GIT_COMMITTER_EMAIL: "bot@users.noreply.github.com"
